### ISSUE TITLE
HU1 - Enrutar vistas

### ISSUE THREAD

**Issue by MayAlcione** [MayAlcione/DEV005-burger-queen-api-client#7]
- [x] Crear rutas al menú.
- [x] Crear ruta a pedidos.
- [x] Crear ruta a cocina.
- [x] Crear ruta a lista de personal.
- [x] Crear ruta a lista de productos.

**Comment by IndiraPe** [comment]
1. Crear el módulo Admin y en la terminal ejecutar:   `ng g m modules/admin --routing`
2. Crear el componente Admin dentro del módulo Admin:    `ng g c modules/admin/admin`
3. Estructura de la carpeta:   `modules>admin>adminrouting.module.ts && admin.module.ts && (admin>componenteAdmin)`
4. Dentro de admin.routing.module.ts =
 `import { AdminComponent } from './admin/admin.component';

const routes: Routes = [{
  path: 'nombre de la subruta',
  component: AdminComponent
}];`
5. Dentro de app-routing.module.ts = 
  `const routes: Routes = [
  { path: 'admin', loadChildren:() => import ('./modules/admin/admin.module').then((m) => m.AdminModule)},
];`
6. En la interfaz al poner: `path/admin` = nos lleva al renderizado del html del componente admin
